// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_components_cpp
Rcpp::List find_components_cpp(const Rcpp::IntegerMatrix& edges, int n_nodes, bool compress);
RcppExport SEXP _graphfast_find_components_cpp(SEXP edgesSEXP, SEXP n_nodesSEXP, SEXP compressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type compress(compressSEXP);
    rcpp_result_gen = Rcpp::wrap(find_components_cpp(edges, n_nodes, compress));
    return rcpp_result_gen;
END_RCPP
}
// are_connected_cpp
Rcpp::LogicalVector are_connected_cpp(const Rcpp::IntegerMatrix& edges, const Rcpp::IntegerMatrix& query_pairs, int n_nodes);
RcppExport SEXP _graphfast_are_connected_cpp(SEXP edgesSEXP, SEXP query_pairsSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type query_pairs(query_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(are_connected_cpp(edges, query_pairs, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// shortest_paths_cpp
Rcpp::IntegerVector shortest_paths_cpp(const Rcpp::IntegerMatrix& edges, const Rcpp::IntegerMatrix& query_pairs, int n_nodes, int max_distance);
RcppExport SEXP _graphfast_shortest_paths_cpp(SEXP edgesSEXP, SEXP query_pairsSEXP, SEXP n_nodesSEXP, SEXP max_distanceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type query_pairs(query_pairsSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< int >::type max_distance(max_distanceSEXP);
    rcpp_result_gen = Rcpp::wrap(shortest_paths_cpp(edges, query_pairs, n_nodes, max_distance));
    return rcpp_result_gen;
END_RCPP
}
// graph_stats_cpp
Rcpp::List graph_stats_cpp(const Rcpp::IntegerMatrix& edges, int n_nodes);
RcppExport SEXP _graphfast_graph_stats_cpp(SEXP edgesSEXP, SEXP n_nodesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    rcpp_result_gen = Rcpp::wrap(graph_stats_cpp(edges, n_nodes));
    return rcpp_result_gen;
END_RCPP
}
// get_edge_components_cpp
Rcpp::List get_edge_components_cpp(const Rcpp::IntegerMatrix& edges, int n_nodes, bool compress);
RcppExport SEXP _graphfast_get_edge_components_cpp(SEXP edgesSEXP, SEXP n_nodesSEXP, SEXP compressSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type edges(edgesSEXP);
    Rcpp::traits::input_parameter< int >::type n_nodes(n_nodesSEXP);
    Rcpp::traits::input_parameter< bool >::type compress(compressSEXP);
    rcpp_result_gen = Rcpp::wrap(get_edge_components_cpp(edges, n_nodes, compress));
    return rcpp_result_gen;
END_RCPP
}
// multi_column_group_cpp
Rcpp::List multi_column_group_cpp(const Rcpp::List& data, const Rcpp::CharacterVector& incomparables, bool case_sensitive, int min_group_size);
RcppExport SEXP _graphfast_multi_column_group_cpp(SEXP dataSEXP, SEXP incomparablesSEXP, SEXP case_sensitiveSEXP, SEXP min_group_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type incomparables(incomparablesSEXP);
    Rcpp::traits::input_parameter< bool >::type case_sensitive(case_sensitiveSEXP);
    Rcpp::traits::input_parameter< int >::type min_group_size(min_group_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(multi_column_group_cpp(data, incomparables, case_sensitive, min_group_size));
    return rcpp_result_gen;
END_RCPP
}
// multi_column_group_numeric_cpp
Rcpp::List multi_column_group_numeric_cpp(const Rcpp::List& data, int min_group_size);
RcppExport SEXP _graphfast_multi_column_group_numeric_cpp(SEXP dataSEXP, SEXP min_group_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type min_group_size(min_group_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(multi_column_group_numeric_cpp(data, min_group_size));
    return rcpp_result_gen;
END_RCPP
}
// ultra_fast_group_numeric_cpp
Rcpp::List ultra_fast_group_numeric_cpp(const Rcpp::List& data, int min_group_size);
RcppExport SEXP _graphfast_ultra_fast_group_numeric_cpp(SEXP dataSEXP, SEXP min_group_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< int >::type min_group_size(min_group_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(ultra_fast_group_numeric_cpp(data, min_group_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_graphfast_find_components_cpp", (DL_FUNC) &_graphfast_find_components_cpp, 3},
    {"_graphfast_are_connected_cpp", (DL_FUNC) &_graphfast_are_connected_cpp, 3},
    {"_graphfast_shortest_paths_cpp", (DL_FUNC) &_graphfast_shortest_paths_cpp, 4},
    {"_graphfast_graph_stats_cpp", (DL_FUNC) &_graphfast_graph_stats_cpp, 2},
    {"_graphfast_get_edge_components_cpp", (DL_FUNC) &_graphfast_get_edge_components_cpp, 3},
    {"_graphfast_multi_column_group_cpp", (DL_FUNC) &_graphfast_multi_column_group_cpp, 4},
    {"_graphfast_multi_column_group_numeric_cpp", (DL_FUNC) &_graphfast_multi_column_group_numeric_cpp, 2},
    {"_graphfast_ultra_fast_group_numeric_cpp", (DL_FUNC) &_graphfast_ultra_fast_group_numeric_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_graphfast(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
