# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find Connected Components
find_components_cpp <- function(edges, n_nodes, compress = TRUE) {
    .Call(`_graphfast_find_components_cpp`, edges, n_nodes, compress)
}

#' Check Connectivity
are_connected_cpp <- function(edges, query_pairs, n_nodes) {
    .Call(`_graphfast_are_connected_cpp`, edges, query_pairs, n_nodes)
}

#' Shortest Paths
shortest_paths_cpp <- function(edges, query_pairs, n_nodes, max_distance) {
    .Call(`_graphfast_shortest_paths_cpp`, edges, query_pairs, n_nodes, max_distance)
}

#' Graph Statistics
graph_stats_cpp <- function(edges, n_nodes) {
    .Call(`_graphfast_graph_stats_cpp`, edges, n_nodes)
}

#' Get Edge Component Assignments
#' 
#' Efficiently returns component ID for each edge (both from and to nodes).
#' This is much faster than doing component lookup in R.
#' 
#' @param edges IntegerMatrix with two columns (from, to)
#' @param n_nodes Number of nodes in the graph
#' @param compress Whether to compress component IDs to consecutive integers
#' @return List with from_components and to_components vectors
get_edge_components_cpp <- function(edges, n_nodes, compress = TRUE) {
    .Call(`_graphfast_get_edge_components_cpp`, edges, n_nodes, compress)
}

#' Multi-Column Group ID Assignment
#'
#' High-performance grouping based on shared values across multiple columns.
#' Uses Union-Find with path compression for optimal performance.
#' Perfect for entity resolution, deduplication, and finding connected records.
#'
#' @param data List of character/numeric vectors representing columns to group by
#' @param incomparables Character vector of values to exclude from grouping (e.g., "", NA, "Unknown")
#' @param case_sensitive Logical. Whether string comparisons should be case sensitive. Default TRUE.
#' @param min_group_size Integer. Minimum group size to assign group ID (smaller groups get ID 0). Default 1.
#'
#' @return List containing:
#' \item{group_ids}{Integer vector of group IDs for each row}
#' \item{n_groups}{Total number of groups found}
#' \item{group_sizes}{Integer vector of group sizes}
#' \item{value_map}{List showing which values belong to which groups}
#'
#' @examples
#' # Phone number matching across columns
#' phone1 <- c("123-456-7890", "987-654-3210", "123-456-7890", "", "555-0123")
#' phone2 <- c("", "987-654-3210", "555-1234", "123-456-7890", "")
#' email <- c("john@email.com", "jane@email.com", "bob@email.com", "john@email.com", "alice@email.com")
#' 
#' result <- multi_column_group_cpp(list(phone1, phone2, email), 
#'                                  incomparables = c("", "NA", "Unknown"))
#'
multi_column_group_cpp <- function(data, incomparables = as.character( c()), case_sensitive = TRUE, min_group_size = 1L) {
    .Call(`_graphfast_multi_column_group_cpp`, data, incomparables, case_sensitive, min_group_size)
}

#' Fast Multi-Column Group ID Assignment for Numeric Data
#'
#' Optimized version for numeric-only columns. Much faster than string-based grouping.
#' 
#' @param data List of numeric/integer vectors
#' @param min_group_size Minimum group size to assign group ID
#' @return List with group_ids, n_groups, group_sizes
multi_column_group_numeric_cpp <- function(data, min_group_size = 1L) {
    .Call(`_graphfast_multi_column_group_numeric_cpp`, data, min_group_size)
}

#' Ultra-Fast Entity Resolution for Large Numeric Datasets
#'
#' Completely different algorithm optimized for millions of records.
#' Uses value-based grouping instead of row-based Union-Find.
#' 
#' @param data List of numeric/integer vectors
#' @param min_group_size Minimum group size to assign group ID
#' @return List with group_ids, n_groups, group_sizes
ultra_fast_group_numeric_cpp <- function(data, min_group_size = 1L) {
    .Call(`_graphfast_ultra_fast_group_numeric_cpp`, data, min_group_size)
}

